# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: RelWithDebInfo # is this even used!?

jobs:
  wasynth:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./Wasynth
    steps:
    - uses: actions/checkout@v3

    - name: Clone Wasynth
      run: git clone https://github.com/Rerumu/Wasynth.git Wasynth

    - name: Toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        target: x86_64-unknown-linux-gnu

    - uses: Swatinem/rust-cache@v1

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --target x86_64-unknown-linux-gnu --bin wasm2luajit --bin wasm2luau --release
  web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: emscripten-core/emsdk
        path: emsdk
    - name: emsdk install
      run: |
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest

    - name: Checkout submodules
      run: |
        cd ../
        git submodule update --init --recursive
    - name: make
      run: |
        source emsdk/emsdk_env.sh
        emcmake cmake . -DCMAKE_BUILD_TYPE=RelWithDebInfo
        cmake --build . --target Luau.LuauCeption.Compiler Luau.LuauCeption.VM Luau.LuauCeption.Full --config RelWithDebInfo -j 2
        ls -la "./"

    - name: convert
      run: |
        ./wasm2luau Luau.LuauCeption.Compiler.wasm > Luau.LuauCeption.Compiler.luau
        ./wasm2luau Luau.LuauCeption.VM.wasm > Luau.LuauCeption.VM.luau
        ./wasm2luau Luau.LuauCeption.Full.wasm > Luau.LuauCeption.Full.luau

    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        name: Luau.LuauCeption
        path: |
          ./Luau.LuauCeption.Compiler.luau
          ./Luau.LuauCeption.VM.luau
          ./Luau.LuauCeption.Full.luau
        overwrite: true
