# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v2
      with:
        repository: emscripten-core/emsdk
        path: emsdk
    - name: emsdk install
      run: |
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
    - name: Add Wasynth
      run: |
        curl -L -o ./wasm2luau https://github.com/Rerumu/Wasynth/releases/latest/download/wasm2luau
        chmod +x ./wasm2luau
        ls -la "./"
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: make
      run: |
        source emsdk/emsdk_env.sh
        emcmake cmake . -DCMAKE_BUILD_TYPE=Release
        cmake --build . --target Luau.LuauCeption.Compiler Luau.LuauCeption.VM Luau.LuauCeption.Full --config Release -j 2
        ls -la "./"
    - name: convert
      run: |
        ./wasm2luau Luau.LuauCeption.Compiler.wasm > Luau.LuauCeption.Compiler.luau
        ./wasm2luau Luau.LuauCeption.VM.wasm > Luau.LuauCeption.VM.luau
        ./wasm2luau Luau.LuauCeption.Full.wasm > Luau.LuauCeption.Full.luau


    - name: Upload files
      uses: actions/upload-artifact@v4
      with:
        name: Luau.LuauCeption
        path: |
          ./Luau.LuauCeption.Compiler.luau
          ./Luau.LuauCeption.VM.luau
          ./Luau.LuauCeption.Full.luau
        overwrite: true
