# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake on a single platform

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/checkout@v2
      with:
        repository: emscripten-core/emsdk
        path: emsdk
    - name: emsdk install
      run: |
        cd emsdk
        ./emsdk install latest
        ./emsdk activate latest
    - name: Add Wasynth
      run: curl -L -o ./utils/wasm2luau https://github.com/Rerumu/Wasynth/releases/latest/download/wasm2luau
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: make
      run: |
        source emsdk/emsdk_env.sh
        emcmake cmake . -DCMAKE_BUILD_TYPE=Release
        cmake --build . --target Luau.LuauCeption.Compiler Luau.LuauCeption.VM Luau.LuauCeption.Full --config Release -j 2
        sh ./utils/Convert.sh
